import { useState, useEffect, useCallback } from "react";
import Head from 'next/head';
import { GameErrorPage } from "components/Errors";
import { RE2RInventory } from "components/Inventory";

//LOCAL JSON SERVER SETTINGS
var JSON_ADDRESS = "127.0.0.1";
const JSON_PORT = 7190;
const POLLING_RATE = 333;
var JSON_ENDPOINT = `http://${JSON_ADDRESS}:${JSON_PORT}/`;

const RE2RItems = () => {
    const [data, setData] = useState(null);
    const [connected, setConnected] = useState(false);

    const appendData = d => {
        if (d === null) return;
        setData(d);
    };

    const handleConnect = useCallback(() => {
        const getData = () => {
            fetch(JSON_ENDPOINT)
                .then(function (response) {
                    return response.json();
                })
                .then(function (data) {
                    setConnected(true);
                    appendData(data);
                })
                .catch(function (err) {
                    console.log("Error: " + err);
                    setConnected(false);
                });
        };
        setInterval(getData, POLLING_RATE);
    }, []);

    useEffect(() => {
        handleConnect();
    }, [handleConnect]);

    if (!connected) return <></>;
    if (data.GameName !== "RE2R") return <GameErrorPage background="bg-re2" callback={handleConnect} />;

    const { Items, InventoryCount } = data;

    return (
        <>
            <Head>
                <title>Stat Tracker | RE2R</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="absolute w-full h-full flex flex-col p-4 gap-2">
                <RE2RInventory items={Items} inventoryCount={InventoryCount} />
            </div>
        </>
    );
}

export default RE2RItems;