import Head from 'next/head';
import HealthBar from "components/HealthBar";
import { TextBlock, TextBlocks } from "components/TextBlock";

const Test = () => {
    function GetColor(state) {
        if (state == "Gassed") return ["bg-rose-900", "text-rose-300"];
        if (state == "Poisoned") return ["bg-indigo-900", "text-indigo-300"];
        if (state == "Fine") return ["bg-green-800", "text-green-300"];
        if (state == "FineToo") return ["bg-green-900", "text-green-300"];
        if (state == "Caution") return ["bg-yellow-800", "text-yellow-300"];
        if (state == "Danger") return ["bg-red-900", "text-red-300"];
        return ["bg-red-900", "text-red-300"];
    }

    return (
        <>
            <Head>
                <title>Stat Tracker | RE4R</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="absolute w-full h-full flex flex-col bg-black p-4 gap-2">
                <TextBlock label="IGT" val="00:00:00.0000" colors={["text-white", "text-green-500"]} hideParam={false} />
                <HealthBar current={1000} max={1000} percent={1} label="Leon" colors={GetColor("Caution")} />
                <TextBlocks labels={["Rank", "ActionPoint", "ItemPoint", "Kills"]} vals={[1, 1, 1, 1]} colors={["text-white", "text-green-500"]} hideParam={false} />
                <HealthBar current={500} max={1000} percent={.5} label="Enemy" colors={GetColor("Danger")} />
            </div>
        </>

    )
}

export default Test;