const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  mode: 'jit',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      gridTemplateRows: {
        '7': 'repeat(7, minmax(0, 1fr))',
        '8': 'repeat(8, minmax(0, 1fr))',
        '9': 'repeat(9, minmax(0, 1fr))',
        '10': 'repeat(10, minmax(0, 1fr))',
        '11': 'repeat(11, minmax(0, 1fr))',
        '12': 'repeat(12, minmax(0, 1fr))',
        '13': 'repeat(13, minmax(0, 1fr))',
        '14': 'repeat(14, minmax(0, 1fr))',
        '15': 'repeat(15, minmax(0, 1fr))',
        '16': 'repeat(16, minmax(0, 1fr))',
        '17': 'repeat(17, minmax(0, 1fr))',
        '18': 'repeat(18, minmax(0, 1fr))',
        '19': 'repeat(19, minmax(0, 1fr))',
        '20': 'repeat(20, minmax(0, 1fr))',
      },
      gridTemplateColumns: {
        '13': 'repeat(13, minmax(0, 1fr))',
        '14': 'repeat(14, minmax(0, 1fr))',
        '15': 'repeat(15, minmax(0, 1fr))',
        '16': 'repeat(16, minmax(0, 1fr))',
        '17': 'repeat(17, minmax(0, 1fr))',
        '18': 'repeat(18, minmax(0, 1fr))',
        '19': 'repeat(19, minmax(0, 1fr))',
        '20': 'repeat(20, minmax(0, 1fr))',
      },
      gridRow: {
        'span-7': 'span 7 / span 7',
        'span-8': 'span 8 / span 8',
        'span-9': 'span 9 / span 9',
        'span-10': 'span 10 / span 10',
        'span-11': 'span 11 / span 11',
        'span-12': 'span 12 / span 12',
        'span-13': 'span 13 / span 13',
        'span-14': 'span 14 / span 14',
        'span-15': 'span 15 / span 15',
        'span-16': 'span 16 / span 16',
        'span-17': 'span 17 / span 17',
        'span-18': 'span 18 / span 18',
        'span-19': 'span 19 / span 19',
        'span-20': 'span 20 / span 20',
      },
      gridColumn: {
        'span-13': 'span 13 / span 13',
        'span-14': 'span 14 / span 14',
        'span-15': 'span 15 / span 15',
        'span-16': 'span 16 / span 16',
        'span-17': 'span 17 / span 17',
        'span-18': 'span 18 / span 18',
        'span-19': 'span 19 / span 19',
        'span-20': 'span 20 / span 20',
      },
      gridColumnStart: {
        '14': '14',
        '15': '15',
        '16': '16',
        '17': '17',
        '18': '18',
        '19': '19',
        '20': '20',
      },
      gridRowStart: {
        '8': '8',
        '9': '9',
        '10': '10',
        '11': '11',
        '12': '12',
        '13': '13',
        '14': '14',
        '15': '15',
        '16': '16',
        '17': '17',
        '18': '18',
        '19': '19',
        '20': '20',
      },
      backgroundImage: {
        "icon": "url('/imgs/icon.png')",
        "main": "url('/imgs/background.jpeg')",
        "re2": "url('/imgs/background2.jpeg')",
        "re3": "url('/imgs/background3.jpg')",
        "re4": "url('/imgs/background.jpeg')",
        "title": "url('/imgs/TitleScreen.png')",
        "eslot1": "url('/imgs/RE2R/EquipSlot1.png')",
        "eslot2": "url('/imgs/RE2R/EquipSlot2.png')",
        "eslot3": "url('/imgs/RE2R/EquipSlot3.png')",
        "eslot4": "url('/imgs/RE2R/EquipSlot4.png')",
        "re2rslot1": "url('/imgs/RE2R/Slot1.png')",
        "re3rslot1": "url('/imgs/RE3R/Slot1.png')",
        "re2rslot2": "url('/imgs/RE2R/Slot2.png')",
        "re3rslot2": "url('/imgs/RE3R/Slot2.png')",
        "re2rempty": "url('/imgs/RE2R/Empty.png')",
        "re3rempty": "url('/imgs/RE3R/Empty.png')",
        "re2requipped": "url('/imgs/RE2R/Equipped.png')",
        "re2rfirstaidspray": "url('/imgs/RE2R/FirstAidSpray.png')",
        "re2rgreenherb": "url('/imgs/RE2R/GreenHerb.png')",
        "re2rredherb": "url('/imgs/RE2R/RedHerb.png')",
        "re2rblueherb": "url('/imgs/RE2R/BlueHerb.png')",
        "re2rmixedherbsgg": "url('/imgs/RE2R/MixedHerbsGG.png')",
        "re2rmixedherbsgr": "url('/imgs/RE2R/MixedHerbsGR.png')",
        "re2rmixedherbsgb": "url('/imgs/RE2R/MixedHerbsGB.png')",
        "re2rmixedherbsggb": "url('/imgs/RE2R/MixedHerbsGGB.png')",
        "re2rmixedherbsggg": "url('/imgs/RE2R/MixedHerbsGGG.png')",
        "re2rmixedherbsgrb": "url('/imgs/RE2R/MixedHerbsGRB.png')",
        "re2rmixedherbsrb": "url('/imgs/RE2R/MixedHerbsRB.png')",
        "re2rgreenherb2": "url('/imgs/RE2R/GreenHerb2.png')",
        "re2rredherb2": "url('/imgs/RE2R/RedHerb2.png')",
        "re2rblueherb2": "url('/imgs/RE2R/BlueHerb2.png')",
        "re2rhandgunammo": "url('/imgs/RE2R/HandgunAmmo.png')",
        "re2rshotgunammo": "url('/imgs/RE2R/ShotgunAmmo.png')",
        "re2rsubmachinegunammo": "url('/imgs/RE2R/SubmachineGunAmmo.png')",
        "re2rmagammo": "url('/imgs/RE2R/MAGAmmo.png')",
        "re2racidrounds": "url('/imgs/RE2R/AcidRounds.png')",
        "re2rflamerounds": "url('/imgs/RE2R/FlameRounds.png')",
        "re2rneedlecartridges": "url('/imgs/RE2R/NeedleCartridges.png')",
        "re2rfuel": "url('/imgs/RE2R/Fuel.png')",
        "re2rhandgunlargecaliberammo": "url('/imgs/RE2R/HandgunLargeCaliberAmmo.png')",
        "re2rsls60highpoweredrounds": "url('/imgs/RE2R/SLS60HighPoweredRounds.png')",
        "re2rdetonator": "url('/imgs/RE2R/Detonator.png')",
        "re2rinkribbon": "url('/imgs/RE2R/InkRibbon.png')",
        "re2rwoodenboard": "url('/imgs/RE2R/WoodenBoard.png')",
        "re2rdetonatornobattery": "url('/imgs/RE2R/DetonatorNoBattery.png')",
        "re2rbattery9volt": "url('/imgs/RE2R/Battery9Volt.png')",
        "re2rgunpowder": "url('/imgs/RE2R/Gunpowder.png')",
        "re2rgunpowderlarge": "url('/imgs/RE2R/GunpowderLarge.png')",
        "re2rgunpowderhighgradeyellow": "url('/imgs/RE2R/GunpowderHighGradeYellow.png')",
        "re2rgunpowderhighgradewhite": "url('/imgs/RE2R/GunpowderHighGradeWhite.png')",
        "re2rmatildahighcapacitymagazine": "url('/imgs/RE2R/MatildaHighCapacityMagazine.png')",
        "re2rmatildamuzzlebrake": "url('/imgs/RE2R/MatildaMuzzleBrake.png')",
        "re2rmatildagunstock": "url('/imgs/RE2R/MatildaGunStock.png')",
        "re2rsls60speedloader": "url('/imgs/RE2R/SLS60SpeedLoader.png')",
        "re2rjmbhp3lasersight": "url('/imgs/RE2R/JMBHp3LaserSight.png')",
        "re2rsls60reinforcedframe": "url('/imgs/RE2R/SLS60ReinforcedFrame.png')",
        "re2rjmbhp3highcapacitymagazine": "url('/imgs/RE2R/JMBHp3HighCapacityMagazine.png')",
        "re2rw870shotgunstock": "url('/imgs/RE2R/W870ShotgunStock.png')",
        "re2rw870longbarrel": "url('/imgs/RE2R/W870LongBarrel.png')",
        "re2rmq11highcapacitymagazine": "url('/imgs/RE2R/MQ11HighCapacityMagazine.png')",
        "re2rmq11suppressor": "url('/imgs/RE2R/MQ11Suppressor.png')",
        "re2rlightninghawkreddotsight": "url('/imgs/RE2R/LightningHawkRedDotSight.png')",
        "re2rlightninghawklongbarrel": "url('/imgs/RE2R/LightningHawkLongBarrel.png')",
        "re2rgm79shoulderstock": "url('/imgs/RE2R/GM79ShoulderStock.png')",
        "re2rflamethrowerregulator": "url('/imgs/RE2R/FlamethrowerRegulator.png')",
        "re2rsparkshothighvoltagecondenser": "url('/imgs/RE2R/SparkShotHighVoltageCondenser.png')",
        "re2rfilmhidingplace": "url('/imgs/RE2R/Film_HidingPlace.png')",
        "re2rfilmrisingrookie": "url('/imgs/RE2R/Film_RisingRookie.png')",
        "re2rfilmcommemorative": "url('/imgs/RE2R/Film_Commemorative.png')",
        "re2rfilm3flocker": "url('/imgs/RE2R/Film_3FLocker.png')",
        "re2rfilmlionstatue": "url('/imgs/RE2R/Film_LionStatue.png')",
        "re2rkeystorageroom": "url('/imgs/RE2R/KeyStorageRoom.png')",
        "re2rjackhandle": "url('/imgs/RE2R/JackHandle.png')",
        "re2rsquarecrank": "url('/imgs/RE2R/SquareCrank.png')",
        "re2rmedallionunicorn": "url('/imgs/RE2R/MedallionUnicorn.png')",
        "re2rkeyspade": "url('/imgs/RE2R/KeySpade.png')",
        "re2rkeycardparkinggarage": "url('/imgs/RE2R/KeyCardParkingGarage.png')",
        "re2rkeycardweaponslocker": "url('/imgs/RE2R/KeyCardWeaponsLocker.png')",
        "re2rvalvehandle": "url('/imgs/RE2R/ValveHandle.png')",
        "re2rstarsbadge": "url('/imgs/RE2R/STARSBadge.png')",
        "re2rscepter": "url('/imgs/RE2R/Scepter.png')",
        "re2rredjewel": "url('/imgs/RE2R/RedJewel.png')",
        "re2rbejeweledbox": "url('/imgs/RE2R/BejeweledBox.png')",
        "re2rplugbishop": "url('/imgs/RE2R/PlugBishop.png')",
        "re2rplugrook": "url('/imgs/RE2R/PlugRook.png')",
        "re2rplugking": "url('/imgs/RE2R/PlugKing.png')",
        "re2rpictureblock": "url('/imgs/RE2R/PictureBlock.png')",
        "re2rusbdonglekey": "url('/imgs/RE2R/USBDongleKey.png')",
        "re2rsparekey": "url('/imgs/RE2R/SpareKey.png')",
        "re2rredbook": "url('/imgs/RE2R/RedBook.png')",
        "re2rstatuesleftarm": "url('/imgs/RE2R/StatuesLeftArm.png')",
        "re2rstatuesleftarmwithredbook": "url('/imgs/RE2R/StatuesLeftArmWithRedBook.png')",
        "re2rmedallionlion": "url('/imgs/RE2R/MedallionLion.png')",
        "re2rkeydiamond": "url('/imgs/RE2R/KeyDiamond.png')",
        "re2rkeycar": "url('/imgs/RE2R/KeyCar.png')",
        "re2rmedallionmaiden": "url('/imgs/RE2R/MedallionMaiden.png')",
        "re2rpowerpanelpart": "url('/imgs/RE2R/PowerPanelPart.png')",
        "re2rpowerpanelpart": "url('/imgs/RE2R/PowerPanelPart.png')",
        "re2rloversrelief": "url('/imgs/RE2R/LoversRelief.png')",
        "re2rgearsmall": "url('/imgs/RE2R/GearSmall.png')",
        "re2rgearlarge": "url('/imgs/RE2R/GearLarge.png')",
        "re2rkeycourtyard": "url('/imgs/RE2R/KeyCourtyard.png')",
        "re2rplugknight": "url('/imgs/RE2R/PlugKnight.png')",
        "re2rplugpawn": "url('/imgs/RE2R/PlugPawn.png')",
        "re2rplugqueen": "url('/imgs/RE2R/PlugQueen.png')",
        "re2rboxedelectronicpart": "url('/imgs/RE2R/BoxedElectronicPart.png')",
        "re2rboxedelectronicpart": "url('/imgs/RE2R/BoxedElectronicPart.png')",
        "re2rkeyorphanage": "url('/imgs/RE2R/KeyOrphanage.png')",
        "re2rkeyclub": "url('/imgs/RE2R/KeyClub.png')",
        "re2rkeyheart": "url('/imgs/RE2R/KeyHeart.png')",
        "re2rdigitalvideocassette": "url('/imgs/RE2R/DigitalVideoCassette.png')",
        "re2rtbarvalvehandle": "url('/imgs/RE2R/TBarValveHandle.png')",
        "re2rdispersalcartridgeempty": "url('/imgs/RE2R/DispersalCartridgeEmpty.png')",
        "re2rdispersalcartridgesolution": "url('/imgs/RE2R/DispersalCartridgeSolution.png')",
        "re2rdispersalcartridgeherbicide": "url('/imgs/RE2R/DispersalCartridgeHerbicide.png')",
        "re2rjointplug": "url('/imgs/RE2R/JointPlug.png')",
        "re2rupgradechipadministrator": "url('/imgs/RE2R/UpgradeChipAdministrator.png')",
        "re2ridwristbandadministrator": "url('/imgs/RE2R/IDWristbandAdministrator.png')",
        "re2relectronicchip": "url('/imgs/RE2R/ElectronicChip.png')",
        "re2rsignalmodulator": "url('/imgs/RE2R/SignalModulator.png')",
        "re2rtrophy": "url('/imgs/RE2R/Trophy.png')",
        "re2rkeysewers": "url('/imgs/RE2R/KeySewers.png')",
        "re2ridwristbandvisitor1": "url('/imgs/RE2R/IDWristbandVisitor1.png')",
        "re2ridwristbandgeneralstaff1": "url('/imgs/RE2R/IDWristbandGeneralStaff1.png')",
        "re2ridwristbandseniorstaff1": "url('/imgs/RE2R/IDWristbandSeniorStaff1.png')",
        "re2rupgradechipgeneralstaff": "url('/imgs/RE2R/UpgradeChipGeneralStaff.png')",
        "re2rupgradechipseniorstaff": "url('/imgs/RE2R/UpgradeChipSeniorStaff.png')",
        "re2ridwristbandvisitor2": "url('/imgs/RE2R/IDWristbandVisitor2.png')",
        "re2ridwristbandgeneralstaff2": "url('/imgs/RE2R/IDWristbandGeneralStaff2.png')",
        "re2ridwristbandseniorstaff2": "url('/imgs/RE2R/IDWristbandSeniorStaff2.png')",
        "re2rdigitalvideocassette": "url('/imgs/RE2R/DigitalVideoCassette.png')",
        "re2rbriefcase": "url('/imgs/RE2R/Briefcase.png')",
        "re2rfusemainhall": "url('/imgs/RE2R/FuseMainHall.png')",
        "re2rfusebreakroom": "url('/imgs/RE2R/FuseBreakRoom.png')",
        "re2rscissors": "url('/imgs/RE2R/Scissors.png')",
        "re2rboltcutters": "url('/imgs/RE2R/BoltCutters.png')",
        "re2rstuffeddoll": "url('/imgs/RE2R/StuffedDoll.png')",
        "re2rhippouch": "url('/imgs/RE2R/HipPouch.png')",
        "re2roldkey": "url('/imgs/RE2R/OldKey.png')",
        "re2rportablesafe": "url('/imgs/RE2R/PortableSafe.png')",
        "re2rtinstoragebox": "url('/imgs/RE2R/TinStorageBox.png')",
        "re2rwoodenbox": "url('/imgs/RE2R/WoodenBox.png')",
        "re2rtinstoragebox": "url('/imgs/RE2R/TinStorageBox.png')",
        "re2rjointplug": "url('/imgs/RE2R/JointPlug.png')",
        "re2rgearlarge": "url('/imgs/RE2R/GearLarge.png')",
        "re2rhandgunmatilda1": "url('/imgs/RE2R/Handgun_Matilda1.png')",
        "re2rhandgunmatilda2": "url('/imgs/RE2R/Handgun_Matilda2.png')",
        "re2rhandgunmatilda3": "url('/imgs/RE2R/Handgun_Matilda3.png')",
        "re2rhandgunmatilda4": "url('/imgs/RE2R/Handgun_Matilda4.png')",
        "re2rhandgunmatilda5": "url('/imgs/RE2R/Handgun_Matilda5.png')",
        "re2rhandgunmatilda6": "url('/imgs/RE2R/Handgun_Matilda6.png')",
        "re2rhandgunmatilda7": "url('/imgs/RE2R/Handgun_Matilda7.png')",
        "re2rhandgunmatilda": "url('/imgs/RE2R/Handgun_Matilda.png')",
        "re2rhandgunm19": "url('/imgs/RE2R/Handgun_M19.png')",
        "re2rhandgunjmbhp31": "url('/imgs/RE2R/Handgun_JMB_Hp3_1.png')",
        "re2rhandgunjmbhp32": "url('/imgs/RE2R/Handgun_JMB_Hp3_2.png')",
        "re2rhandgunjmbhp33": "url('/imgs/RE2R/Handgun_JMB_Hp3_3.png')",
        "re2rhandgunjmbhp3": "url('/imgs/RE2R/Handgun_JMB_Hp3.png')",
        "re2rhandgunquickdraw_army": "url('/imgs/RE2R/Handgun_Quickdraw_Army.png')",
        "re2rhandgunmup": "url('/imgs/RE2R/Handgun_MUP.png')",
        "re2rhandgunbroomhc": "url('/imgs/RE2R/Handgun_BroomHc.png')",
        "re2rhandgunsls601": "url('/imgs/RE2R/Handgun_SLS601.png')",
        "re2rhandgunsls60": "url('/imgs/RE2R/Handgun_SLS60.png')",
        "re2rshotgunw8701": "url('/imgs/RE2R/Shotgun_W8701.png')",
        "re2rshotgunw8702": "url('/imgs/RE2R/Shotgun_W8702.png')",
        "re2rshotgunw8703": "url('/imgs/RE2R/Shotgun_W8703.png')",
        "re2rshotgunw870": "url('/imgs/RE2R/Shotgun_W870.png')",
        "re2rsmgmq111": "url('/imgs/RE2R/SMG_MQ11_1.png')",
        "re2rsmgmq112": "url('/imgs/RE2R/SMG_MQ11_2.png')",
        "re2rsmgmq113": "url('/imgs/RE2R/SMG_MQ11_3.png')",
        "re2rsmgmq11": "url('/imgs/RE2R/SMG_MQ11.png')",
        "re2rsmgle5infinite": "url('/imgs/RE2R/SMG_LE5_Infinite.png')",
        "re2rhandgunlightninghawk1": "url('/imgs/RE2R/Handgun_LightningHawk1.png')",
        "re2rhandgunlightninghawk2": "url('/imgs/RE2R/Handgun_LightningHawk2.png')",
        "re2rhandgunlightninghawk3": "url('/imgs/RE2R/Handgun_LightningHawk3.png')",
        "re2rhandgunlightninghawk": "url('/imgs/RE2R/Handgun_LightningHawk.png')",
        "re2remfvisualizer": "url('/imgs/RE2R/EMF_Visualizer.png')",
        "re2rgrenadelaunchergm791": "url('/imgs/RE2R/GrenadeLauncher_GM791.png')",
        "re2rgrenadelaunchergm79": "url('/imgs/RE2R/GrenadeLauncher_GM79.png')",
        "re2rchemicalflamethrower2": "url('/imgs/RE2R/ChemicalFlamethrower2.png')",
        "re2rchemicalflamethrower": "url('/imgs/RE2R/ChemicalFlamethrower.png')",
        "re2rsparkshot1": "url('/imgs/RE2R/SparkShot1.png')",
        "re2rsparkshot": "url('/imgs/RE2R/SparkShot.png')",
        "re2ratm4": "url('/imgs/RE2R/ATM4.png')",
        "re2rcombatknife": "url('/imgs/RE2R/CombatKnife.png')",
        "re2rcombatknifeinfinite": "url('/imgs/RE2R/CombatKnife_Infinite.png')",
        "re2rantitankrocketlauncher": "url('/imgs/RE2R/AntiTankRocketLauncher.png')",
        "re2rminigun": "url('/imgs/RE2R/Minigun.png')",
        "re2rhandgrenade": "url('/imgs/RE2R/HandGrenade.png')",
        "re2rflashgrenade": "url('/imgs/RE2R/FlashGrenade.png')",
        "re2rhandgunsamuraiedgeinfinite": "url('/imgs/RE2R/Handgun_SamuraiEdge_Infinite.png')",
        "re2rhandgunsamuraiedgechrisredfield": "url('/imgs/RE2R/Handgun_SamuraiEdge_ChrisRedfield.png')",
        "re2rhandgunsamuraiedgejillvalentine": "url('/imgs/RE2R/Handgun_SamuraiEdge_JillValentine.png')",
        "re2rhandgunsamuraiedgealbertwesker": "url('/imgs/RE2R/Handgun_SamuraiEdge_AlbertWesker.png')",
        "re2ratm4": "url('/imgs/RE2R/ATM4.png')",
        "re2rantitankrocketlauncher": "url('/imgs/RE2R/AntiTankRocketLauncher.png')",
        "re2rre2rminigun": "url('/imgs/RE2R/Minigun.png')",
        "re3rfirstaidspray": "url('/imgs/RE3R/FirstAidSpray.png')",
        "re3rgreenherb": "url('/imgs/RE3R/GreenHerb.png')",
        "re3rredherb": "url('/imgs/RE3R/RedHerb.png')",
        "re3rmixedherbsgg": "url('/imgs/RE3R/MixedHerbsGG.png')",
        "re3rmixedherbsgr": "url('/imgs/RE3R/MixedHerbsGR.png')",
        "re3rmixedherbsggg": "url('/imgs/RE3R/MixedHerbsGGG.png')",
        "re3rgreenherb2": "url('/imgs/RE3R/GreenHerb2.png')",
        "re3rredherb2": "url('/imgs/RE3R/RedHerb2.png')",
        "re3rhandgunammo": "url('/imgs/RE3R/HandgunAmmo.png')",
        "re3rshotgunammo": "url('/imgs/RE3R/ShotgunAmmo.png')",
        "re3rassaultrifleammo": "url('/imgs/RE3R/AssaultRifleAmmo.png')",
        "re3rmagammo": "url('/imgs/RE3R/MAGAmmo.png')",
        "re3rminerounds": "url('/imgs/RE3R/MineRounds.png')",
        "re3rassaultrifleammo": "url('/imgs/RE3R/AssaultRifleAmmo.png')",
        "re3rexplosiverounds": "url('/imgs/RE3R/ExplosiveRounds.png')",
        "re3racidrounds": "url('/imgs/RE3R/AcidRounds.png')",
        "re3rflamerounds": "url('/imgs/RE3R/FlameRounds.png')",
        "re3rgunpowder": "url('/imgs/RE3R/Gunpowder.png')",
        "re3rhighgradegunpowder": "url('/imgs/RE3R/HighGradeGunpowder.png')",
        "re3rexplosivea": "url('/imgs/RE3R/ExplosiveA.png')",
        "re3rexplosiveb": "url('/imgs/RE3R/ExplosiveB.png')",
        "re3rmoderatorhandgun": "url('/imgs/RE3R/ModeratorHandgun.png')",
        "re3rdotsighthandgun": "url('/imgs/RE3R/DotSightHandgun.png')",
        "re3rextendedmagazinehandgun": "url('/imgs/RE3R/ExtendedMagazineHandgun.png')",
        "re3rsemiautobarrel": "url('/imgs/RE3R/SemiAutoBarrel.png')",
        "re3rtacticalstockshotgun": "url('/imgs/RE3R/TacticalStockShotgun.png')",
        "re3rshellholdershotgun": "url('/imgs/RE3R/ShellHolderShotgun.png')",
        "re3rscopeassaultrifle": "url('/imgs/RE3R/ScopeAssaultRifle.png')",
        "re3rdualmagazineassaultrifle": "url('/imgs/RE3R/DualMagazineAssaultRifle.png')",
        "re3rtacticalgripassaultrifle": "url('/imgs/RE3R/TacticalGripAssaultRifle.png')",
        "re3rexbarrelmag": "url('/imgs/RE3R/ExBarrelMAG.png')",
        "re3raudiocassettetape": "url('/imgs/RE3R/AudiocassetteTape.png')",
        "re3rlockpick": "url('/imgs/RE3R/LockPick.png')",
        "re3rboltcutters": "url('/imgs/RE3R/BoltCutters.png')",
        "re3rbattery": "url('/imgs/RE3R/Battery.png')",
        "re3rsafetydepositkey": "url('/imgs/RE3R/SafetyDepositKey.png')",
        "re3rbradsidcard": "url('/imgs/RE3R/BradsIDCard.png')",
        "re3rdetonatornobattery": "url('/imgs/RE3R/DetonatorNoBattery.png')",
        "re3rdetonator": "url('/imgs/RE3R/Detonator.png')",
        "re3rfirehose": "url('/imgs/RE3R/FireHose.png')",
        "re3rkendosgatekey": "url('/imgs/RE3R/KendosGateKey.png')",
        "re3rcaselockpick": "url('/imgs/RE3R/CaseLockPick.png')",
        "re3rbatterypack": "url('/imgs/RE3R/BatteryPack.png')",
        "re3rgreenjewel": "url('/imgs/RE3R/GreenJewel.png')",
        "re3rbluejewel": "url('/imgs/RE3R/BlueJewel.png')",
        "re3rredjewel": "url('/imgs/RE3R/RedJewel.png')",
        "re3rfancybox": "url('/imgs/RE3R/FancyBox.png')",
        "re3rhospitalidcard": "url('/imgs/RE3R/HospitalIDCard.png')",
        "re3rtapeplayertapeinserted": "url('/imgs/RE3R/TapePlayerTapeInserted.png')",
        "re3raudiocassettetape": "url('/imgs/RE3R/AudiocassetteTape.png')",
        "re3rtapeplayer": "url('/imgs/RE3R/TapePlayer.png')",
        "re3rvaccinesample": "url('/imgs/RE3R/VaccineSample.png')",
        "re3rdetonator": "url('/imgs/RE3R/Detonator.png')",
        "re3rlockerroomkey": "url('/imgs/RE3R/LockerRoomKey.png')",
        "re3rfuse3": "url('/imgs/RE3R/Fuse3.png')",
        "re3rfuse2": "url('/imgs/RE3R/Fuse2.png')",
        "re3rfuse1": "url('/imgs/RE3R/Fuse1.png')",
        "re3rflashdrive": "url('/imgs/RE3R/FlashDrive.png')",
        "re3rvaccine": "url('/imgs/RE3R/Vaccine.png')",
        "re3rculturesample": "url('/imgs/RE3R/CultureSample.png')",
        "re3rliquidfilledtesttube": "url('/imgs/RE3R/LiquidFilledTestTube.png')",
        "re3rvaccinebase": "url('/imgs/RE3R/VaccineBase.png')",
        "re3rirondefensecoin": "url('/imgs/RE3R/IronDefenseCoin.png')",
        "re3rassaultcoin": "url('/imgs/RE3R/AssaultCoin.png')",
        "re3rrecoverycoin": "url('/imgs/RE3R/RecoveryCoin.png')",
        "re3rcraftingcompanion": "url('/imgs/RE3R/CraftingCompanion.png')",
        "re3rstarsfieldcombatmanual": "url('/imgs/RE3R/STARSFieldCombatManual.png')",
        "re3rsupplycrate": "url('/imgs/RE3R/SupplyCrate.png')",
        "re3rg19handgun1": "url('/imgs/RE3R/G19Handgun1.png')",
        "re3rg19handgun2": "url('/imgs/RE3R/G19Handgun2.png')",
        "re3rg19handgun3": "url('/imgs/RE3R/G19Handgun3.png')",
        "re3rg19handgun4": "url('/imgs/RE3R/G19Handgun4.png')",
        "re3rg19handgun5": "url('/imgs/RE3R/G19Handgun5.png')",
        "re3rg19handgun6": "url('/imgs/RE3R/G19Handgun6.png')",
        "re3rg19handgun7": "url('/imgs/RE3R/G19Handgun7.png')",
        "re3rg19handgun": "url('/imgs/RE3R/G19Handgun.png')",
        "re3rg18bursthandgun": "url('/imgs/RE3R/G18BurstHandgun.png')",
        "re3rg18handgun": "url('/imgs/RE3R/G18Handgun.png')",
        "re3rsamuraiedge": "url('/imgs/RE3R/SamuraiEdge.png')",
        "re3rinfinitemuphandgun": "url('/imgs/RE3R/InfiniteMUPHandgun.png')",
        "re3rm3shotgun1": "url('/imgs/RE3R/M3Shotgun1.png')",
        "re3rm3shotgun2": "url('/imgs/RE3R/M3Shotgun2.png')",
        "re3rm3shotgun3": "url('/imgs/RE3R/M3Shotgun3.png')",
        "re3rm3shotgun4": "url('/imgs/RE3R/M3Shotgun4.png')",
        "re3rm3shotgun5": "url('/imgs/RE3R/M3Shotgun5.png')",
        "re3rm3shotgun6": "url('/imgs/RE3R/M3Shotgun6.png')",
        "re3rm3shotgun7": "url('/imgs/RE3R/M3Shotgun7.png')",
        "re3rm3shotgun": "url('/imgs/RE3R/M3Shotgun.png')",
        "re3rinfinitecqbrassaultrifle": "url('/imgs/RE3R/InfiniteCQBRAssaultRifle.png')",
        "re3rcqbrassaultrifle1": "url('/imgs/RE3R/CQBRAssaultRifle1.png')",
        "re3rcqbrassaultrifle2": "url('/imgs/RE3R/CQBRAssaultRifle2.png')",
        "re3rcqbrassaultrifle3": "url('/imgs/RE3R/CQBRAssaultRifle3.png')",
        "re3rcqbrassaultrifle4": "url('/imgs/RE3R/CQBRAssaultRifle4.png')",
        "re3rcqbrassaultrifle5": "url('/imgs/RE3R/CQBRAssaultRifle5.png')",
        "re3rcqbrassaultrifle6": "url('/imgs/RE3R/CQBRAssaultRifle6.png')",
        "re3rcqbrassaultrifle7": "url('/imgs/RE3R/CQBRAssaultRifle7.png')",
        "re3rcqbrassaultrifle": "url('/imgs/RE3R/CQBRAssaultRifle.png')",
        "re3rlightninghawk1": "url('/imgs/RE3R/LightningHawk1.png')",
        "re3rlightninghawk": "url('/imgs/RE3R/LightningHawk.png')",
        "re3rraiden": "url('/imgs/RE3R/RAIDEN.png')",
        "re3rmglgrenadelauncher": "url('/imgs/RE3R/MGLGrenadeLauncher.png')",
        "re3rcombatknife": "url('/imgs/RE3R/CombatKnife.png')",
        "re3rsurvivalknife": "url('/imgs/RE3R/SurvivalKnife.png')",
        "re3rhotdogger": "url('/imgs/RE3R/HotDogger.png')",
        "re3rrocketlauncher": "url('/imgs/RE3R/RocketLauncher.png')",
        "re3rhandgrenade": "url('/imgs/RE3R/HandGrenade.png')",
        "re3rflashgrenade": "url('/imgs/RE3R/FlashGrenade.png')",
        "re4rslots": "url('/imgs/RE4R/Slots.png')",
        "re4rhandgunammo": "url('/imgs/RE4R/HandgunAmmo.png')",
        "re4rshotgunammo": "url('/imgs/RE4R/ShotgunShells.png')",
        "re4rsubmachinegunammo": "url('/imgs/RE4R/SubmachineGunAmmo.png')",
        "re4rrifleammo": "url('/imgs/RE4R/RifleAmmo.png')",
        "re4rgreenherb": "url('/imgs/RE4R/GreenHerb.png')",
        "re4rredherb": "url('/imgs/RE4R/RedHerb.png')",
        "re4ryellowherb": "url('/imgs/RE4R/YellowHerb.png')",
        "re4rmixedherbsgg": "url('/imgs/RE4R/MixedHerbsGG.png')",
        "re4rmixedherbsgr": "url('/imgs/RE4R/MixedHerbsGR.png')",
        "re4rmixedherbsggg": "url('/imgs/RE4R/MixedHerbsGGG.png')",
        "re4rmixedherbsgy": "url('/imgs/RE4R/MixedHerbsGY.png')",
        "re4rmixedherbsry": "url('/imgs/RE4R/MixedHerbsRY.png')",
        "re4rmixedherbsggy": "url('/imgs/RE4R/MixedHerbsGGY.png')",
        "re4rmixedherbsgry": "url('/imgs/RE4R/MixedHerbsGRY.png')",
        "re4rkitchenknife": "url('/imgs/RE4R/KitchenKnife.png')",
        "re4rresourcess": "url('/imgs/RE4R/ResourcesS.png')",
        "re4rresourcesl": "url('/imgs/RE4R/ResourcesL.png')",
        "re4rgunpowder": "url('/imgs/RE4R/Gunpowder.png')",
        "re4rchickenegg": "url('/imgs/RE4R/ChickenEgg.png')",
        "re4rbrownchickenegg": "url('/imgs/RE4R/BrownChickenEgg.png')",
        "re4rgoldchickenegg": "url('/imgs/RE4R/GoldChickenEgg.png')",
        "re4rrocketlauncher": "url('/imgs/RE4R/RocketLauncher.png')",
        "re4rsg09r": "url('/imgs/RE4R/SG09R.png')",
        "re4rtmp": "url('/imgs/RE4R/TMP.png')",
        "re4rsentinelnine": "url('/imgs/RE4R/SentinelNine.png')",
        "re4rboltthrower": "url('/imgs/RE4R/BoltThrower.png')",
        "re4rskullshaker": "url('/imgs/RE4R/SkullShaker.png')",
        "re4rw870": "url('/imgs/RE4R/W870.png')",
        "re4rcombatknife": "url('/imgs/RE4R/CombatKnife.png')",
        "re4rflashgrenade": "url('/imgs/RE4R/FlashGrenade.png')",
        "re4rhandgrenade": "url('/imgs/RE4R/HandGrenade.png')",
        "re4rred9": "url('/imgs/RE4R/Red9.png')",
        "re4rred9": "url('/imgs/RE4R/Red9.png')",
        "re4rattachablemines": "url('/imgs/RE4R/AttachableMines.png')",
        "re4rriotgun": "url('/imgs/RE4R/RiotGun.png')",
        "re4rbolts": "url('/imgs/RE4R/Bolts.png')",
        "re4rblacktail": "url('/imgs/RE4R/Blacktail.png')",
        "re4rbrokenbutterfly": "url('/imgs/RE4R/BrokenButterfly.png')",
        "re4rstingray": "url('/imgs/RE4R/Stingray.png')",
        "re4rbootknife": "url('/imgs/RE4R/BootKnife.png')",
        "re4rmagnumammo": "url('/imgs/RE4R/MagnumAmmo.png')",
        "re4rscope": "url('/imgs/RE4R/Scope.png')",
        "re4rsrm1903": "url('/imgs/RE4R/SRM1903.png')",
        "re4rheavygrenade": "url('/imgs/RE4R/HeavyGrenade.png')",
        "re4rcqbrassaultrifle": "url('/imgs/RE4R/CQBRAssaultRifle.png')",
        "re4rstriker": "url('/imgs/RE4R/Striker.png')",
        "re4rfirstaidspray": "url('/imgs/RE4R/FirstAidSpray.png')",
        "re4rblackbass": "url('/imgs/RE4R/BlackBass.png')",
        "re4rcubicdevice": "url('/imgs/RE4R/CubicDevice.png')",
        "re4rsilvertoken": "url('/imgs/RE4R/SilverToken.png')",
        "re4rgoldtoken": "url('/imgs/RE4R/GoldToken.png')",
        "re4rhunterslodgekey": "url('/imgs/RE4R/HuntersLodgeKey.png')",
        "re4rinsigniakey": "url('/imgs/RE4R/InsigniaKey.png')",
        "re4rdungeonkey": "url('/imgs/RE4R/DungeonKey.png')",
        "re4rhexagonpiecec": "url('/imgs/RE4R/HexagonPieceC.png')",
        "re4roldwayshrinekey": "url('/imgs/RE4R/OldWayshrineKey.png')",
        "re4rluiskey": "url('/imgs/RE4R/LuisKey.png')",
        "re4rsmallkey": "url('/imgs/RE4R/SmallKey.png')",
        "re4rlevel1keycard": "url('/imgs/RE4R/Level1Keycard.png')",
        "re4rlevel2keycard": "url('/imgs/RE4R/Level2Keycard.png')",
        "re4rlevel3keycard": "url('/imgs/RE4R/Level3Keycard.png')",
        "re4rkiller7": "url('/imgs/RE4R/Killer7.png')",
        "re4rle5": "url('/imgs/RE4R/LE5.png')",
        "re4rbiosensorcope": "url('/imgs/RE4R/BiosensorScope.png')",
        "re4rwrench": "url('/imgs/RE4R/Wrench.png')",
        "re4rfightingknife": "url('/imgs/RE4R/FightingKnife.png')",
        "re4rviper": "url('/imgs/RE4R/Viper.png')",
      }
    }
  },
  variants: {
    textFillColor: ['responsive'],
    extends: {
      backgroundColor: ['checked', 'first', 'last', 'even', 'odd'],
      padding: ['responsive', 'first', 'last'],
      margin: ['responsive', 'first', 'last'],
    },
  },
  plugins: [],
}
