const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  mode: 'jit',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      gridTemplateRows: {
        // Simple 8 row grid
        '8': 'repeat(8, minmax(0, 1fr))',
        '9': 'repeat(9, minmax(0, 1fr))',
        '10': 'repeat(10, minmax(0, 1fr))',
        '11': 'repeat(11, minmax(0, 1fr))',
        '12': 'repeat(12, minmax(0, 1fr))',
      },
      gridRow: {
        'span-7': 'span 7 / span 7',
        'span-8': 'span 8 / span 8',
        'span-9': 'span 9 / span 9',
        'span-10': 'span 10 / span 10',
        'span-11': 'span 11 / span 11',
        'span-12': 'span 12 / span 12',
      },
      backgroundImage: {
        "icon": "url('/imgs/icon.png')",
        "main": "url('/imgs/background.jpeg')",
        "re2": "url('/imgs/background2.jpeg')",
        "re3": "url('/imgs/background3.jpg')",
        "re4": "url('/imgs/background.jpeg')",
        "title": "url('/imgs/TitleScreen.png')",
        "re2rslot1": "url('/imgs/RE2R/Slot1.png')",
        "re2rslot2": "url('/imgs/RE2R/Slot2.png')",
        "re2rfirstaidspray": "url('/imgs/RE2R/FirstAidSpray.png')",
        "re2rgreenherb": "url('/imgs/RE2R/GreenHerb.png')",
        "re2rredherb": "url('/imgs/RE2R/RedHerb.png')",
        "re2rblueherb": "url('/imgs/RE2R/BlueHerb.png')",
        "re2rmixedherbsgg": "url('/imgs/RE2R/MixedHerbsGG.png')",
        "re2rmixedherbsgr": "url('/imgs/RE2R/MixedHerbsGR.png')",
        "re2rmixedherbsgb": "url('/imgs/RE2R/MixedHerbsGB.png')",
        "re2rmixedherbsggb": "url('/imgs/RE2R/MixedHerbsGGB.png')",
        "re2rmixedherbsggg": "url('/imgs/RE2R/MixedHerbsGGG.png')",
        "re2rmixedherbsgrb": "url('/imgs/RE2R/MixedHerbsGRB.png')",
        "re2rmixedherbsrb": "url('/imgs/RE2R/MixedHerbsRB.png')",
        "re2rgreenherb2": "url('/imgs/RE2R/GreenHerb2.png')",
        "re2rredherb2": "url('/imgs/RE2R/RedHerb2.png')",
        "re2rblueherb2": "url('/imgs/RE2R/BlueHerb2.png')",
        "re2rhandgunammo": "url('/imgs/RE2R/HandgunAmmo.png')",
        "re2rshotgunammo": "url('/imgs/RE2R/ShotgunAmmo.png')",
        "re2rsubmachinegunammo": "url('/imgs/RE2R/SubmachineGunAmmo.png')",
        "re2rmagammo": "url('/imgs/RE2R/MAGAmmo.png')",
        "re2racidrounds": "url('/imgs/RE2R/AcidRounds.png')",
        "re2rflamerounds": "url('/imgs/RE2R/FlameRounds.png')",
        "re2rneedlecartridges": "url('/imgs/RE2R/NeedleCartridges.png')",
        "re2rfuel": "url('/imgs/RE2R/Fuel.png')",
        "re2rhandgunlargecaliberammo": "url('/imgs/RE2R/HandgunLargeCaliberAmmo.png')",
        "re2rsls60highpoweredrounds": "url('/imgs/RE2R/SLS60HighPoweredRounds.png')",
        "re2rdetonator": "url('/imgs/RE2R/Detonator.png')",
        "re2rinkribbon": "url('/imgs/RE2R/InkRibbon.png')",
        "re2rwoodenboard": "url('/imgs/RE2R/WoodenBoard.png')",
        "re2rdetonatornobattery": "url('/imgs/RE2R/DetonatorNoBattery.png')",
        "re2rbattery9volt": "url('/imgs/RE2R/Battery9Volt.png')",
        "re2rgunpowder": "url('/imgs/RE2R/Gunpowder.png')",
        "re2rgunpowderlarge": "url('/imgs/RE2R/GunpowderLarge.png')",
        "re2rgunpowderhighgradeyellow": "url('/imgs/RE2R/GunpowderHighGradeYellow.png')",
        "re2rgunpowderhighgradewhite": "url('/imgs/RE2R/GunpowderHighGradeWhite.png')",
        "re2rmatildahighcapacitymagazine": "url('/imgs/RE2R/MatildaHighCapacityMagazine.png')",
        "re2rmatildamuzzlebrake": "url('/imgs/RE2R/MatildaMuzzleBrake.png')",
        "re2rmatildagunstock": "url('/imgs/RE2R/MatildaGunStock.png')",
        "re2rsls60speedloader": "url('/imgs/RE2R/SLS60SpeedLoader.png')",
        "re2rjmbhp3lasersight": "url('/imgs/RE2R/JMBHp3LaserSight.png')",
        "re2rsls60reinforcedframe": "url('/imgs/RE2R/SLS60ReinforcedFrame.png')",
        "re2rjmbhp3highcapacitymagazine": "url('/imgs/RE2R/JMBHp3HighCapacityMagazine.png')",
        "re2rw870shotgunstock": "url('/imgs/RE2R/W870ShotgunStock.png')",
        "re2rw870longbarrel": "url('/imgs/RE2R/W870LongBarrel.png')",
        "re2rmq11highcapacitymagazine": "url('/imgs/RE2R/MQ11HighCapacityMagazine.png')",
        "re2rmq11suppressor": "url('/imgs/RE2R/MQ11Suppressor.png')",
        "re2rlightninghawkreddotsight": "url('/imgs/RE2R/LightningHawkRedDotSight.png')",
        "re2rlightninghawklongbarrel": "url('/imgs/RE2R/LightningHawkLongBarrel.png')",
        "re2rgm79shoulderstock": "url('/imgs/RE2R/GM79ShoulderStock.png')",
        "re2rflamethrowerregulator": "url('/imgs/RE2R/FlamethrowerRegulator.png')",
        "re2rsparkshothighvoltagecondenser": "url('/imgs/RE2R/SparkShotHighVoltageCondenser.png')",
        "re2rfilmhidingplace": "url('/imgs/RE2R/Film_HidingPlace.png')",
        "re2rfilmrisingrookie": "url('/imgs/RE2R/Film_RisingRookie.png')",
        "re2rfilmcommemorative": "url('/imgs/RE2R/Film_Commemorative.png')",
        "re2rfilm3flocker": "url('/imgs/RE2R/Film_3FLocker.png')",
        "re2rfilmlionstatue": "url('/imgs/RE2R/Film_LionStatue.png')",
        "re2rkeystorageroom": "url('/imgs/RE2R/KeyStorageRoom.png')",
        "re2rjackhandle": "url('/imgs/RE2R/JackHandle.png')",
        "re2rsquarecrank": "url('/imgs/RE2R/SquareCrank.png')",
        "re2rmedallionunicorn": "url('/imgs/RE2R/MedallionUnicorn.png')",
        "re2rkeyspade": "url('/imgs/RE2R/KeySpade.png')",
        "re2rkeycardparkinggarage": "url('/imgs/RE2R/KeyCardParkingGarage.png')",
        "re2rkeycardweaponslocker": "url('/imgs/RE2R/KeyCardWeaponsLocker.png')",
        "re2rvalvehandle": "url('/imgs/RE2R/ValveHandle.png')",
        "re2rstarsbadge": "url('/imgs/RE2R/STARSBadge.png')",
        "re2rscepter": "url('/imgs/RE2R/Scepter.png')",
        "re2rredjewel": "url('/imgs/RE2R/RedJewel.png')",
        "re2rbejeweledbox": "url('/imgs/RE2R/BejeweledBox.png')",
        "re2rplugbishop": "url('/imgs/RE2R/PlugBishop.png')",
        "re2rplugrook": "url('/imgs/RE2R/PlugRook.png')",
        "re2rplugking": "url('/imgs/RE2R/PlugKing.png')",
        "re2rpictureblock": "url('/imgs/RE2R/PictureBlock.png')",
        "re2rusbdonglekey": "url('/imgs/RE2R/USBDongleKey.png')",
        "re2rsparekey": "url('/imgs/RE2R/SpareKey.png')",
        "re2rredbook": "url('/imgs/RE2R/RedBook.png')",
        "re2rstatuesleftarm": "url('/imgs/RE2R/StatuesLeftArm.png')",
        "re2rstatuesleftarmwithredbook": "url('/imgs/RE2R/StatuesLeftArmWithRedBook.png')",
        "re2rmedallionlion": "url('/imgs/RE2R/MedallionLion.png')",
        "re2rkeydiamond": "url('/imgs/RE2R/KeyDiamond.png')",
        "re2rkeycar": "url('/imgs/RE2R/KeyCar.png')",
        "re2rmedallionmaiden": "url('/imgs/RE2R/MedallionMaiden.png')",
        "re2rpowerpanelpart": "url('/imgs/RE2R/PowerPanelPart.png')",
        "re2rpowerpanelpart": "url('/imgs/RE2R/PowerPanelPart.png')",
        "re2rloversrelief": "url('/imgs/RE2R/LoversRelief.png')",
        "re2rgearsmall": "url('/imgs/RE2R/GearSmall.png')",
        "re2rgearlarge": "url('/imgs/RE2R/GearLarge.png')",
        "re2rkeycourtyard": "url('/imgs/RE2R/KeyCourtyard.png')",
        "re2rplugknight": "url('/imgs/RE2R/PlugKnight.png')",
        "re2rplugpawn": "url('/imgs/RE2R/PlugPawn.png')",
        "re2rplugqueen": "url('/imgs/RE2R/PlugQueen.png')",
        "re2rboxedelectronicpart": "url('/imgs/RE2R/BoxedElectronicPart.png')",
        "re2rboxedelectronicpart": "url('/imgs/RE2R/BoxedElectronicPart.png')",
        "re2rkeyorphanage": "url('/imgs/RE2R/KeyOrphanage.png')",
        "re2rkeyclub": "url('/imgs/RE2R/KeyClub.png')",
        "re2rkeyheart": "url('/imgs/RE2R/KeyHeart.png')",
        "re2rdigitalvideocassette": "url('/imgs/RE2R/DigitalVideoCassette.png')",
        "re2rdispersalcartridgeempty": "url('/imgs/RE2R/DispersalCartridgeEmpty.png')",
        "re2rdispersalcartridgesolution": "url('/imgs/RE2R/DispersalCartridgeSolution.png')",
        "re2rdispersalcartridgeherbicide": "url('/imgs/RE2R/DispersalCartridgeHerbicide.png')",
        "re2rjointplug": "url('/imgs/RE2R/JointPlug.png')",
        "re2rupgradechipadministrator": "url('/imgs/RE2R/UpgradeChipAdministrator.png')",
        "re2ridwristbandadministrator": "url('/imgs/RE2R/IDWristbandAdministrator.png')",
        "re2relectronicchip": "url('/imgs/RE2R/ElectronicChip.png')",
        "re2rsignalmodulator": "url('/imgs/RE2R/SignalModulator.png')",
        "re2rtrophy": "url('/imgs/RE2R/Trophy.png')",
        "re2rkeysewers": "url('/imgs/RE2R/KeySewers.png')",
        "re2ridwristbandvisitor1": "url('/imgs/RE2R/IDWristbandVisitor1.png')",
        "re2ridwristbandgeneralstaff1": "url('/imgs/RE2R/IDWristbandGeneralStaff1.png')",
        "re2ridwristbandseniorstaff1": "url('/imgs/RE2R/IDWristbandSeniorStaff1.png')",
        "re2rupgradechipgeneralstaff": "url('/imgs/RE2R/UpgradeChipGeneralStaff.png')",
        "re2rupgradechipseniorstaff": "url('/imgs/RE2R/UpgradeChipSeniorStaff.png')",
        "re2ridwristbandvisitor2": "url('/imgs/RE2R/IDWristbandVisitor2.png')",
        "re2ridwristbandgeneralstaff2": "url('/imgs/RE2R/IDWristbandGeneralStaff2.png')",
        "re2ridwristbandseniorstaff2": "url('/imgs/RE2R/IDWristbandSeniorStaff2.png')",
        "re2rdigitalvideocassette": "url('/imgs/RE2R/DigitalVideoCassette.png')",
        "re2rbriefcase": "url('/imgs/RE2R/Briefcase.png')",
        "re2rfusemainhall": "url('/imgs/RE2R/FuseMainHall.png')",
        "re2rfusebreakroom": "url('/imgs/RE2R/FuseBreakRoom.png')",
        "re2rscissors": "url('/imgs/RE2R/Scissors.png')",
        "re2rboltcutters": "url('/imgs/RE2R/BoltCutters.png')",
        "re2rstuffeddoll": "url('/imgs/RE2R/StuffedDoll.png')",
        "re2rhippouch": "url('/imgs/RE2R/HipPouch.png')",
        "re2roldkey": "url('/imgs/RE2R/OldKey.png')",
        "re2rportablesafe": "url('/imgs/RE2R/PortableSafe.png')",
        "re2rtinstoragebox": "url('/imgs/RE2R/TinStorageBox.png')",
        "re2rwoodenbox": "url('/imgs/RE2R/WoodenBox.png')",
        "re2rtinstoragebox": "url('/imgs/RE2R/TinStorageBox.png')",
        "re2rjointplug": "url('/imgs/RE2R/JointPlug.png')",
        "re2rgearlarge": "url('/imgs/RE2R/GearLarge.png')",
        "re2rhandgunmatilda1": "url('/imgs/RE2R/Handgun_Matilda1.png')",
        "re2rhandgunmatilda2": "url('/imgs/RE2R/Handgun_Matilda2.png')",
        "re2rhandgunmatilda3": "url('/imgs/RE2R/Handgun_Matilda3.png')",
        "re2rhandgunmatilda4": "url('/imgs/RE2R/Handgun_Matilda4.png')",
        "re2rhandgunmatilda5": "url('/imgs/RE2R/Handgun_Matilda5.png')",
        "re2rhandgunmatilda6": "url('/imgs/RE2R/Handgun_Matilda6.png')",
        "re2rhandgunmatilda7": "url('/imgs/RE2R/Handgun_Matilda7.png')",
        "re2rhandgunmatilda": "url('/imgs/RE2R/Handgun_Matilda.png')",
        "re2rhandgunm19": "url('/imgs/RE2R/Handgun_M19.png')",
        "re2rhandgunjmbhp31": "url('/imgs/RE2R/Handgun_JMB_Hp3_1.png')",
        "re2rhandgunjmbhp32": "url('/imgs/RE2R/Handgun_JMB_Hp3_2.png')",
        "re2rhandgunjmbhp33": "url('/imgs/RE2R/Handgun_JMB_Hp3_3.png')",
        "re2rhandgunjmbhp3": "url('/imgs/RE2R/Handgun_JMB_Hp3.png')",
        "re2rhandgunquickdraw_army": "url('/imgs/RE2R/Handgun_Quickdraw_Army.png')",
        "re2rhandgunmup": "url('/imgs/RE2R/Handgun_MUP.png')",
        "re2rhandgunbroomhc": "url('/imgs/RE2R/Handgun_BroomHc.png')",
        "re2rhandgunsls601": "url('/imgs/RE2R/Handgun_SLS601.png')",
        "re2rhandgunsls60": "url('/imgs/RE2R/Handgun_SLS60.png')",
        "re2rshotgunw8701": "url('/imgs/RE2R/Shotgun_W8701.png')",
        "re2rshotgunw8702": "url('/imgs/RE2R/Shotgun_W8702.png')",
        "re2rshotgunw8703": "url('/imgs/RE2R/Shotgun_W8703.png')",
        "re2rshotgunw870": "url('/imgs/RE2R/Shotgun_W870.png')",
        "re2rsmgmq111": "url('/imgs/RE2R/SMG_MQ11_1.png')",
        "re2rsmgmq112": "url('/imgs/RE2R/SMG_MQ11_2.png')",
        "re2rsmgmq113": "url('/imgs/RE2R/SMG_MQ11_3.png')",
        "re2rsmgmq11": "url('/imgs/RE2R/SMG_MQ11.png')",
        "re2rsmgle5infinite": "url('/imgs/RE2R/SMG_LE5_Infinite.png')",
        "re2rhandgunlightninghawk1": "url('/imgs/RE2R/Handgun_LightningHawk1.png')",
        "re2rhandgunlightninghawk2": "url('/imgs/RE2R/Handgun_LightningHawk2.png')",
        "re2rhandgunlightninghawk3": "url('/imgs/RE2R/Handgun_LightningHawk3.png')",
        "re2rhandgunlightninghawk": "url('/imgs/RE2R/Handgun_LightningHawk.png')",
        "re2remfvisualizer": "url('/imgs/RE2R/EMF_Visualizer.png')",
        "re2rgrenadelaunchergm791": "url('/imgs/RE2R/GrenadeLauncher_GM791.png')",
        "re2rgrenadelaunchergm79": "url('/imgs/RE2R/GrenadeLauncher_GM79.png')",
        "re2rchemicalflamethrower2": "url('/imgs/RE2R/ChemicalFlamethrower2.png')",
        "re2rchemicalflamethrower": "url('/imgs/RE2R/ChemicalFlamethrower.png')",
        "re2rsparkshot1": "url('/imgs/RE2R/SparkShot1.png')",
        "re2rsparkshot": "url('/imgs/RE2R/SparkShot.png')",
        "re2ratm4": "url('/imgs/RE2R/ATM4.png')",
        "re2rcombatknife": "url('/imgs/RE2R/CombatKnife.png')",
        "re2rcombatknifeinfinite": "url('/imgs/RE2R/CombatKnife_Infinite.png')",
        "re2rantitankrocketlauncher": "url('/imgs/RE2R/AntiTankRocketLauncher.png')",
        "re2rminigun": "url('/imgs/RE2R/Minigun.png')",
        "re2rhandgrenade": "url('/imgs/RE2R/HandGrenade.png')",
        "re2rflashgrenade": "url('/imgs/RE2R/FlashGrenade.png')",
        "re2rhandgunsamuraiedgeinfinite": "url('/imgs/RE2R/Handgun_SamuraiEdge_Infinite.png')",
        "re2rhandgunsamuraiedgechrisredfield": "url('/imgs/RE2R/Handgun_SamuraiEdge_ChrisRedfield.png')",
        "re2rhandgunsamuraiedgejillvalentine": "url('/imgs/RE2R/Handgun_SamuraiEdge_JillValentine.png')",
        "re2rhandgunsamuraiedgealbertwesker": "url('/imgs/RE2R/Handgun_SamuraiEdge_AlbertWesker.png')",
        "re2ratm4": "url('/imgs/RE2R/ATM4.png')",
        "re2rantitankrocketlauncher": "url('/imgs/RE2R/AntiTankRocketLauncher.png')",
        "re2rre2rminigun": "url('/imgs/RE2R/Minigun.png')"
      }
    }
  },
  variants: {
    textFillColor: ['responsive'],
    extends: {
      backgroundColor: ['checked', 'first', 'last', 'even', 'odd'],
      padding: ['responsive', 'first', 'last'],
      margin: ['responsive', 'first', 'last'],
    },
  },
  plugins: [],
}
