import { useState, useEffect, useCallback } from "react";
import Head from 'next/head';
import { ErrorPage, GameErrorPage } from "components/Errors";
import HealthBar from "components/HealthBar";
import { TextBlock, TextBlocks } from "components/TextBlock";

const websocket_endpoint = "wss://relay.aricodes.net/ws"; // 'ws://localhost:19906';

const Asc = (a, b) => {
    if (a > b) return +1;
    if (a < b) return -1;
    return 0;
};

const Desc = (a, b) => {
    if (a > b) return -1;
    if (a < b) return +1;
    return 0;
};

const RE4RWS = () => {
    const [data, setData] = useState(null);
    const [connected, setConnected] = useState(false);
    const [input, setInput] = useState(null);
    const [token, setToken] = useState(null);

    const handleConnect = useCallback(() => {
        const appendData = d => {
            if (d === null) return;
            setData(d);
            if (process.env.NODE_ENV !== 'production') console.log("Websocket Data: ", d);
        };

        const socket = new WebSocket(websocket_endpoint);
        socket.onopen = () => {
            socket.send(`listen:${token}`);
            setConnected(true);
        };
        socket.onclose = () => {
            setConnected(false);
        };
        socket.onmessage = event => appendData(JSON.parse(event.data));
    }, [token, setConnected, setData]);

    useEffect(() => {
        handleConnect();
    }, [handleConnect]);

    function GetColor(state) {
        if (state == "Gassed") return ["bg-rose-900", "text-rose-300"];
        if (state == "Poisoned") return ["bg-indigo-900", "text-indigo-300"];
        if (state == "Fine") return ["bg-green-800", "text-green-300"];
        if (state == "FineToo") return ["bg-green-900", "text-green-300"];
        if (state == "Caution") return ["bg-yellow-800", "text-yellow-300"];
        return ["bg-red-900", "text-red-300"];
    }

    if (token === null) return (
        <div className="absolute w-full h-full flex flex-col justify-center items-center p-4">
            <div className="bg-slate-900 w-full max-w-xl flex flex-col justify-center items-start p-8 gap-2">
                <div className="text-gray-200">Please Enter token:</div>
                <input className="w-full leading-8 pl-2" type="text" onChange={(e) => setInput(e.target.value)} />
                <button className="w-full h-8 bg-green-800 hover:bg-green-600 text-gray-200 rounded-md" type="button" onClick={() => setToken(input)}>Submit</button>
            </div>
        </div>
    );
    if (!connected) return <ErrorPage background="bg-re" connected={connected} callback={handleConnect} />;
    if (data.GameName !== "RE4R") return <GameErrorPage background="bg-re" callback={handleConnect} />;

    const { PlayerHealth, Rank, GameStatsKillCountElement, EnemyHealth, IGTFormattedString } = data;
    const { CurrentHitPoint, DefaultHitPoint, Percentage, CurrentHealthState } = PlayerHealth;
    const { Rank: _Rank, ActionPoint, ItemPoint } = Rank;
    const { Count } = GameStatsKillCountElement;

    const filterdEnemies = EnemyHealth.filter(m => { return (m.IsAlive) }).sort(function (a, b) {
        return Asc(a.CurrentHitPoint, b.CurrentHitPoint) || Desc(a.CurrentHitPoint, b.CurrentHitPoint);
    });

    return (
        <>
            <Head>
                <title>Stat Tracker | RE4R</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="absolute w-full h-full flex">
                <TextBlock label="IGT" val={IGTFormattedString} colors={["text-white", "text-green-500"]} hideParam={false} />
                <HealthBar current={CurrentHitPoint} max={DefaultHitPoint} percent={Percentage} label="Leon" colors={GetColor(CurrentHealthState)} />
                <TextBlocks labels={["Rank", "ActionPoint", "ItemPoint", "Kills"]} vals={[_Rank, ActionPoint, ItemPoint, Count]} colors={["text-white", "text-green-500"]} hideParam={false} />
                {filterdEnemies.map((enemy, idx) => (
                    <HealthBar key={`enemy${idx}`} current={enemy.CurrentHitPoint} max={enemy.DefaultHitPoint} percent={enemy.Percentage} label="" colors={["bg-red-900", "text-red-500"]} />
                ))}
            </div>
        </>
    );
}

export default RE4RWS;